FROM node:16-alpine as build-step

RUN mkdir /app

WORKDIR /app

COPY ./audio-classification/package.json /app

RUN npm install

COPY ./audio-classification /app

EXPOSE 4200

RUN npm run build --prod

FROM nginx:1.17.1-alpine

COPY --from=build-step /app/dist/audio-classification /usr/share/nginx/html

