version: '3.7'

# Services
services:

  backend_flask:
    build:
      context: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./data:/usr/src/

  frontend_angular:
    build:
      context: ./frontend
    ports:
      - 4200:80
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d

  