version: '3.7'

# Services
services:

  backend_flask:
    build:
      context: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/usr/src/app


  frontend_angular:
    build:
      context: ./frontend
    ports:
      - 4200:4200
    links:
      - backend_flask


  